version: 0.2

phases:
  install:
    commands:
      - echo installing nodejs...
      - sudo apt-get install -y nodejs  #aws code build use ubuntu environement
      - sudo apt install -y npm
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
      - npm -f install
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ng build --prod
artifacts:
  files:
    - "**/*"
  discard-paths: no
