version: 0.2

phases:
  install:
    commands:
      - echo installing nodejs...
      - sudo apt update
      - sudo apt install nodejs -y #aws code build use ubuntu environement
      
  pre_build:
    commands:
      - echo installing dependencies...
      - npm i -g @angular/cli
